### PR TITLE
Module is working now

### PR DESCRIPTION
**Pull request by WebCrew**
Hi @Felli I updated a lot of the code and now the module is working. The only thing which is left to do is to:

replace line 11 of widgets/views/discordappframe.php with your code and then your mopdule is finish and ready to use :+1: 

Greetz :)

### CODE REVIEW

**Comment by Felli** [comment]
Thanks! :smile: I planned on fixing the admin panel so that all you'll need to do is add the link within the iframe code then save it, but never got around to doing so.

**Comment by WebCrew** [comment]
Yeahh thats a amacing idea! I hope you`ll get it done. If you know how to do such a task let me jknow it too please. All my module does have only basic admin settings and it would be great to do the needed things from HH backend :)

**Comment by Felli** [comment]
I have a basic design down, but making it work is somewhat of a problem because it gives off errors in the admin logs so when I'm finished I'll post them on this module and tag you in it. :+1:

**Comment by WebCrew** [comment]
yeah that would be great. I think one could do it a bit similar to Twig Framework and one has to use "placeholders" something like `{discord_server_ID}` together with the PHP `include` feature.

SettingsForm.php and AdminController.php has to be used to handle it and to integrate the missing features.

**Comment by Felli** [comment]
Yes those would have to be added in the long run of things.

**Pull request merged**
